version: '3.8'
services:
  server:
    build:
      dockerfile: Dockerfile
    image: server
    container_name: login-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  db:
    image: postgres:13.7-alpine
    container_name: server-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot